config/routes.rb
Manage::Application.routes.draw do
  get "session/login"

  get "session/logout"

  resources :students do 
      member do
         get 'activate'
         get 'destroy_record'
      end
  as_routes end

  resources :branches do as_routes end

  resources :genders do as_routes end

  match '/login' => 'session#login'

   root :to => 'session#login'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :description, :name
  has_one :student
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :name
  has_one :student
end

app/models/hits.rb
class Hits < ActiveRecord::Base
  attr_accessible :count
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name
  has_one :user
  Admin=1
  Faculty=2
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_uniqueness_of :rollno
  attr_accessible :branch_id, :firstname, :gender_id, :lastname, :rollno, :status
  acts_as_paranoid :column => 'status', :column_type =>'string', :deleted_value => 'deleted'

belongs_to :gender
belongs_to :branch

def self.only_deleted
  without_paranoid_default_scope.where("#{paranoid_column_reference} IS NOT ?", nil)
end


end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
 include BCrypt
 attr_accessible :encrypted_password, :role_id, :username
 belongs_to :role

def password
  @password ||=Password.new(encrypted_password)
end

def password=(value)
  @password=Password.create(value)
  self.encrypted_password=@password
end
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # Check whether session is empty or not
  def require_login
    if session[:user_id].nil?
        @message="You must Log-In to access this content"
        redirect_to "/login"
    end
  end

  # Clear cache to avoid navigating back after logout
  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
  end

  # Check wether the logged-in user is a Admin or Faculty
  def isAdmin
    @user=User.find(session[:user_id])
      if @user.role_id == Role::Admin
        true
      else
       false
      end
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  active_scaffold :"branch" do |conf|
  end
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  active_scaffold :"gender" do |conf|
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
   if session[:user_id]!=nil
         redirect_to("/students")
   else
     if params[:post]
         @user=User.where(:username => params[:post][:username]).first
         if !@user.nil? && @user.password == params[:post][:password]
          session[:user_id]=@user.id
          session[:display_name]=@user.username
          redirect_to("/students")
         else
          @message="Unauthorized User"
          render "login"
         end
     end
   end
  end

  def logout
   reset_session
   @hits=Hits.find(1)
   @hits.count+=1
   @hits.save
   redirect_to "/login"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
before_filter :set_cache_buster,:require_login,:student_config
   active_scaffold :"student" do |conf|
    conf.label="Student Details"
    conf.actions=[:create,:list,:search,:update,:delete,:subform]
    conf.delete.refresh_list = true
    conf.columns=[:rollno,:firstname,:lastname,:gender,:branch,:status]
    conf.search.columns = [:firstname,:lastname]
    conf.columns[:gender].clear_link
    conf.columns[:branch].clear_link
    conf.search.live=true
    conf.list.always_show_search=true
    conf.list.per_page = 25
    conf.action_links.add 'activate', :label => 'Activate', :type => :record, :confirm => 'Do you want to restore record?', :page => true
    conf.action_links.add 'destroy_record', :label => 'Destroy', :type => :record, :confirm => 'Do you want to remove record from Database?', :page => true
 end

   # Overriding Active Scaffolds method to select only active records when faculty logs in 
   # and select all records(both active and incative) when admin logs in.
   def beginning_of_chain
     if isAdmin
       active_scaffold_config.model.with_deleted
    else
      active_scaffold_config.model
    end
  end


  # Remove record from Database(Real Deletion)
  def destroy_record
   @record=Student.only_deleted.find(params[:id])
   flash[:info] = "Record with Firstname #{@record.firstname} has been Removed from Database"
   @record.destroy
   return_to_main
  end

  # Restore the deleted record
  def activate
    @record=Student.only_deleted.find(params[:id])
      flash[:info] = "Record with Firstname #{@record.firstname} has been Restored"
    @record.recover
  return_to_main
  end

  # Configure Active Scaffold for Students Controller based on Logged-in user role 
  def student_config
    # Exclude Status column for creat and update action
    active_scaffold_config.create.columns.exclude :status
    active_scaffold_config.update.columns.exclude :status
    # Show Status Column if the logged-in user is Admin else exclude it
    if isAdmin
      active_scaffold_config.list.columns.add :status
    else
      active_scaffold_config.list.columns.exclude :status
    end
  end

  # Overriding Active Sacffold method to allow delete action for Admin 
  def delete_authorized? record=nil
   isAdmin
  end

  # Overriding Active Scaffold method to allow create action for Admin
  def create_authorized? record=nil
   isAdmin
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  # Display active image if the record is a active record else display inactive image
  def status_column record, column
    record.status.nil? ? image_tag("active.png") : image_tag("inactive.png")
  end

end

app/views/active_scaffold_overrides/_list_record.html.erb
<%
record = list_record if list_record # compat with render :partial :collection
columns ||= list_columns
tr_class = cycle("", "even-record") + ' ' + list_row_class(record)
if record.class.paranoid?
  if record.status.nil?
    action_links ||= active_scaffold_config.action_links.member
  else  
   action_links = active_scaffold_config.action_links.record
  end
else
action_links = active_scaffold_config.action_links.member
end
data_refresh ||= url_for(params_for(:action => :row, :id => '--ID--', :_method => :get))

-%>
<tr class="record <%= tr_class %>" id="<%= element_row_id(:action => :list, :id => record.id) %>" data-refresh="<%= data_refresh.sub('--ID--', record.id.to_s) %>">
  <% columns.each do |column| %>
    <% authorized = record.authorized_for?(:crud_type => :read, :column => column.name) -%>
    <% column_value = authorized ? get_column_value(record, column) : active_scaffold_config.list.empty_field_text -%>

    <%= content_tag :td, column_attributes(column, record).merge(:class => column_class(column, column_value, record)) do %>
      <%= authorized ? render_list_column(column_value, column, record) : column_value %>
    <% end %>
  <% end -%>
    
  <td class="actions"><table>
    <tr>
      <td class="indicator-container">
        <%= loading_indicator_tag(:action => :record, :id => record.id) %>
      </td>
      <%= display_action_links(action_links, record, :level_0_tag => :td, :for => record.persisted? ? record : record.class) %>
    </tr>
  </table></td>

  
  <%= render_nested_view(action_links, record) unless @nested_auto_open.nil? %>
</tr>

app/views/active_scaffold_overrides/_list_with_header.html.erb
<% debugger %>
<div id="<%= active_scaffold_id -%>" class="<%= as_main_div_class %> scaffold_width" <%= "data-eid=#{id_from_controller(params[:eid])}" if params[:eid]%>>
  <div class="active-scaffold-header">
    <%= render :partial => 'list_header' %>
  </div>
<table>
    <tbody class="before-header" id="<%= before_header_id -%>">
</tbody>
</table>
<div id="<%= active_scaffold_content_id-%>" class="as_content">
    <%= render :partial => 'list' %>
  </div>
</div>

app/views/active_scaffold_overrides/edit_associated.js.erb
<%
associated_form = render :partial => "form_association_record", :object => @record, :locals => {:scope => @scope, :parent_record => @parent_record, :column => @column}
#:locked => @record.new_record? && @column.singular_association?}
options = {:singular => false}
if @column.singular_association?
  options[:singular] = true
else
  unless @record.new_record?
    column = active_scaffold_config_for(@record.class).columns[@record.class.primary_key]
    options[:id] = active_scaffold_input_options(column, column_scope(@column, @scope, @record))[:id]
  end
end %>
ActiveScaffold.create_associated_record_form('<%=sub_form_list_id(:association => @column.name, :id => @parent_record.id || generated_id(@parent_record) || 99999999999)%>','<%=escape_javascript(associated_form)%>', <%= options.to_json.html_safe %>);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/students.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% debugger %>
<% if !session[:user_id].nil? %>
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
   <a class="navbar-brand git" href="https://github.com/ami1906/manage" target="_blank"><%=image_tag("github.png",:size => "50x50")%>Paranoid Scaffold</a>
  </div>
  <div class="collapse navbar-collapse" >
      <div class="navbar-form navbar-left" role="search">
<%live_search = active_scaffold_config.search.live? %>
<% id = session[:user_id] %>
 <%= form_tag students_path,:id => 'as_students-search--form', :class => 'as_form',:remote => true, :method => 'get'%>
     <%=text_field_tag 'search',nil, :id => 'as_students-search-input', :placeholder => 'Search using Name', :class => 'form-control size', :autocomplete => :off %>
     <%= submit_tag as_(:search), :class => "submit" %>
        <%= link_to "Reset","/students?search=", :class =>"reset_pad", :remote => true, :data => {:refresh =>true} %>
    </form>
 
</div>
    <ul class="nav navbar-nav navbar-right">
<li><a href="#">Welcome <%= session[:display_name].camelize%></a></li>
  <li><%= link_to "<span class='glyphicon glyphicon-log-out font-logout'></span>".html_safe, controller: "session", action: "logout" %>
</li>
   
    </ul>
  </div>
</nav>

<% end %>
<%= yield %>

<script type="text/javascript">
//<![CDATA[
<% if !id.nil? %>
<% if live_search && ActiveScaffold.js_framework == :jquery %>
 jQuery(<%= "##{search_input_id}".to_json.html_safe %>).next().hide();
  jQuery(<%= "##{search_input_id}".to_json.html_safe %>).delayedObserver(0.5, function() {
     jQuery(<%= "##{search_input_id}".to_json.html_safe %>).parent().trigger("submit");
});
<% end -%>
ActiveScaffold.focus_first_element_of_form('<%= element_form_id(:action => 'search') %>');
<% end %>
//]]>
</script>

</body>
</html>

app/views/session/login.html.erb
<style>
body {
     padding-top: 40px;
     padding-bottom: 40px;
     background-color: #f5f5f5;
}
</style>
<div class="container">
<%= form_for :post, url:"login", :html=>{:class=>"form-signin",:role=>"form"} do |f|%>
 <h2 class="form-signin-heading text-center">Please sign in</h2>
 <% if @message %>
 <div class="alert alert-danger">
 <%= @message %>
 </div>
 <% end %>
 <%= f.text_field(:username,:class => "form-control",:placeholder=>"User Name") %>
 <%= f.password_field(:password,:class => "form-control",:placeholder=>"Password") %>
 <p class="text-center"><%= f.button "Sign In",:type=>"submit",:class=>"btn btn-large btn-primary" %></p>
<% end %>
<div class="notes">
<p> This app is a demonstration of <b>Paranoid</b> and <b>Active Scaffold</b> Gem </p>
<p> <b>Roles:</b> Admin, Faculty </p>
<p><b>Admin:</b> Can do the CRUDR(Create, Read/View, Update/Edit, Delete, Restore) operation on Student Record</p>
<p> <b>Faculty:</b> Can do the RU(Read/View, Update/Edit) operation on Student Record</p>
<table class="table table-bordered">
<tr>
<td><b> Role </b></td>
<td><b> User Name </b></td>
<td><b> Password </b></td>
</tr>
<tr>
<td><b> Admin</b> </td>
<td> admin </td>
<td> admin</td>
</tr>
<tr>
<td><b> Faculty</b> </td>
<td> faculty </td>
<td> faculty </td>
</tr>

</table>
<table class="table table-bordered">
<tr class="active">
<td>
<%= link_to "About Author", "http://amarnathks.wordpress.com/about/",:target => "_blank" %>
</td>
<td>
<b>Total Visits:</b> <%= Hits.find(1).count %>
</td>
<td>
<%= link_to "Source Code", "https://github.com/ami1906/manage", :target => "_blank" %>
</td></tr>
<table>
</div>
</div>
 

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>